# Archlinux
# Build Piqi from release tag and publish .zst package
# Based on: https://github.com/Bali10050/Darkly/blob/main/.github/workflows/archlinux.yml

on:
  push:
    tags:
      - "*"
env:
  PKGBUILD: $GITHUB_WORKSPACE/.github/assets/PKGBUILD
jobs:
  build:
    runs-on: ubuntu-24.04
    container: archlinux:latest
    steps:
      - name: Checkout local
        uses: actions/checkout@v4.2.0
        with:
          repository: ${{ github.repository }}
          sparse-checkout: .github
          sparse-checkout-cone-mode: false
      - name: System update
        run: pacman -Syu --noconfirm
      - name: Install sudo, git and compile dependencies
        # Using qcoro as the only dependency (qt6-declarative and qt6-base are implicit deps)
        run: |
          pacman -Sy sudo git binutils make gcc pkg-config fakeroot debugedit \
          cmake extra-cmake-modules ninja qcoro --noconfirm
      - name: Setup build user
        run: |
          useradd builduser -m # Create the builduser
          passwd -d builduser # Delete the buildusers password
          printf 'builduser ALL=(ALL) ALL\n' | tee -a /etc/sudoers # Allow the builduser passwordless sudo
      - name: Update PKGBUILD file with new checksum and git tag values
        run: |
          tag_version="${GITHUB_REF#refs/tags/}"
          mkdir /var/tmp/piqi-archlinux
          cp ${{ env.PKGBUILD }} /var/tmp/piqi-archlinux
          sed -i "s/.*pkgver=.*/pkgver=${tag_version}/" /var/tmp/piqi-archlinux/PKGBUILD
      - name: Change permissions of build directory
        run: |
          chown builduser:builduser -R /var/tmp/piqi-archlinux
        # run: sudo -u builduser bash -c 'cd /var/tmp/piqi-archlinux; makepkg -g >> PKGBUILD'
      # - name: Generate package checksum
      - name: Build package
        run: |
          tag_version="${GITHUB_REF#refs/tags/}"
          sudo -u builduser bash -c 'cd /var/tmp/piqi-archlinux; makepkg -s'
          zst_file=$(find /var/tmp/piqi-archlinux -name "*.zst*")
          publish_filename=piqi-${tag_version}-1-x86_64.pkg.tar.zst
          mv "$zst_file" $publish_filename
          echo "ZST_ASSET=$publish_filename" >> "$GITHUB_ENV"
      - name: Release
        uses: softprops/action-gh-release@v2.0.8
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ env.ZST_ASSET }}
